// LoRAEvaluator.swift - Automated LoRA training evaluation pipeline
// Copyright 2025 Vincent Gourbin

import Foundation
import MLX
import FluxTextEncoders
import CoreGraphics
import ImageIO

// MARK: - Evaluation Results

/// Result of LoRA evaluation pipeline
public struct LoRAEvaluation: @unchecked Sendable {
    public let sceneScore: Int
    public let styleScore: Int
    public let sceneReason: String
    public let styleReason: String
    public let description: String
    public let baselineImage: CGImage
    public let recommendation: LoRARecommendation
}

/// Recommended LoRA training parameters based on evaluation
public struct LoRARecommendation: Sendable {
    public let steps: Int
    public let rank: Int
    public let alpha: Float
    public let learningRate: Float
    public let warmupSteps: Int
    public let timestepSampling: String
    public let lossWeighting: String
    public let targetLayers: String
    public let useDOP: Bool
    public let dopClass: String?
    public let useGradientCheckpointing: Bool
    public let summary: String

    /// Export as YAML training config
    public func toYAML(model: Flux2Model, triggerWord: String, datasetPath: String = "./dataset") -> String {
        var yaml = """
        # LoRA Training Config — Auto-generated by evaluate-lora
        # \(summary)

        model:
          name: \(model.rawValue)
          quantization: bf16

        lora:
          rank: \(rank)
          alpha: \(alpha)
          target_layers: \(targetLayers)

        training:
          batch_size: 1
          max_steps: \(steps)
          warmup_steps: \(warmupSteps)
          learning_rate: \(learningRate)
          weight_decay: 0.0001

        loss:
          weighting: \(lossWeighting)
          timestep_sampling: \(timestepSampling)
        """

        if useDOP {
            yaml += "\n  diff_output_preservation: true"
            if let cls = dopClass {
                yaml += "\n  diff_output_preservation_class: \"\(cls)\""
            }
            yaml += "\n  diff_output_preservation_multiplier: 1.0"
        }

        yaml += """


        memory:
          gradient_checkpointing: \(useGradientCheckpointing)
          cache_latents: true
          cache_text_embeddings: true
          bucketing:
            enabled: true
            resolutions: [512, 768]

        dataset:
          path: \(datasetPath)
          trigger_word: \(triggerWord)
        """

        return yaml
    }
}

// MARK: - Evaluator

/// Automated LoRA training evaluation pipeline
/// Analyzes a reference image, generates a baseline with the base model,
/// compares them, and recommends training parameters.
public class LoRAEvaluator {

    public init() {}

    /// Run the full evaluation pipeline
    /// - Parameters:
    ///   - referenceImage: The target image to train towards
    ///   - model: Which FLUX.2 model to evaluate (klein-4b, klein-9b, dev)
    ///   - quantization: Quantization config for inference
    ///   - seed: Random seed for reproducible baseline generation
    ///   - width: Baseline image width
    ///   - height: Baseline image height
    ///   - hfToken: HuggingFace token for gated models
    ///   - onProgress: Progress callback
    public func evaluate(
        referenceImage: CGImage,
        model: Flux2Model,
        quantization: Flux2QuantizationConfig = .init(textEncoder: .mlx8bit, transformer: .qint8),
        seed: UInt64 = 42,
        width: Int = 512,
        height: Int = 512,
        hfToken: String? = nil,
        onProgress: (@Sendable (String) -> Void)? = nil
    ) async throws -> LoRAEvaluation {

        // === Step 1: VLM describes reference image ===
        onProgress?("[1/4] Analyzing reference image with VLM...")

        // Load VLM if not already loaded
        if !FluxTextEncoders.shared.isQwen35VLMLoaded {
            onProgress?("  Loading Qwen3.5 VLM...")
            let downloader = TextEncoderModelDownloader()
            let vlmPath = try await downloader.downloadQwen35(variant: .qwen35_4B_4bit)
            try await FluxTextEncoders.shared.loadQwen35VLM(from: vlmPath.path)
        }

        let descResult = try FluxTextEncoders.shared.describeImageForFlux(image: referenceImage)
        let description = descResult.text
        onProgress?("  Description: \"\(description.prefix(80))...\"")

        // Unload VLM to free memory for generation
        await MainActor.run { FluxTextEncoders.shared.unloadQwen35VLM() }
        Memory.clearCache()

        // === Step 2: Generate baseline image with base model ===
        onProgress?("[2/4] Generating baseline image (\(width)x\(height), seed=\(seed))...")

        let pipeline = Flux2Pipeline(model: model, quantization: quantization, hfToken: hfToken)

        let steps = model.defaultSteps
        let guidance = model.defaultGuidance

        let baselineImage = try await pipeline.generateTextToImage(
            prompt: description,
            height: height,
            width: width,
            steps: steps,
            guidance: guidance,
            seed: seed
        ) { current, total in
            onProgress?("  Step \(current)/\(total)")
        }

        // Unload pipeline to free memory for VLM comparison
        // (pipeline deallocates when it goes out of scope, but let's be explicit)
        Memory.clearCache()

        // === Step 3: VLM compares reference vs baseline ===
        onProgress?("[3/4] Comparing reference vs baseline...")

        // Reload VLM
        if !FluxTextEncoders.shared.isQwen35VLMLoaded {
            let downloader = TextEncoderModelDownloader()
            let vlmPath = try await downloader.downloadQwen35(variant: .qwen35_4B_4bit)
            try await FluxTextEncoders.shared.loadQwen35VLM(from: vlmPath.path)
        }

        let comparison = try FluxTextEncoders.shared.compareImagesForFlux(
            reference: referenceImage,
            generated: baselineImage
        )

        onProgress?("  Scene: \(comparison.sceneScore)/10 — \(comparison.sceneReason)")
        onProgress?("  Style: \(comparison.styleScore)/10 — \(comparison.styleReason)")

        // Unload VLM
        await MainActor.run { FluxTextEncoders.shared.unloadQwen35VLM() }

        // === Step 4: Generate recommendation ===
        onProgress?("[4/4] Generating training recommendation...")

        let recommendation = computeRecommendation(
            sceneScore: comparison.sceneScore,
            styleScore: comparison.styleScore,
            model: model
        )

        onProgress?("  \(recommendation.summary)")

        return LoRAEvaluation(
            sceneScore: comparison.sceneScore,
            styleScore: comparison.styleScore,
            sceneReason: comparison.sceneReason,
            styleReason: comparison.styleReason,
            description: description,
            baselineImage: baselineImage,
            recommendation: recommendation
        )
    }

    // MARK: - Recommendation Logic

    private func computeRecommendation(sceneScore: Int, styleScore: Int, model: Flux2Model) -> LoRARecommendation {
        let sceneGap = 10 - max(0, sceneScore)
        let styleGap = 10 - max(0, styleScore)
        let totalGap = sceneGap + styleGap
        let needsGradientCheckpoint = model == .dev || model == .klein9B || model == .klein9BBase

        // Steps based on total gap
        let steps: Int
        let rank: Int

        switch totalGap {
        case 0...4:   // Very close (both 8-10)
            steps = 150; rank = 8
        case 5...8:   // Moderate gap
            steps = 400; rank = 16
        case 9...12:  // Significant gap
            steps = 750; rank = 32
        case 13...16: // Large gap
            steps = 1200; rank = 48
        default:      // Maximum gap
            steps = 2000; rank = 64
        }

        // Timestep sampling based on which dimension needs more work
        let timestepSampling: String
        if sceneGap > styleGap + 2 {
            timestepSampling = "content"  // Focus on subjects/objects
        } else if styleGap > sceneGap + 2 {
            timestepSampling = "style"    // Focus on visual style
        } else {
            timestepSampling = "balanced" // Both need work
        }

        // DOP when scene needs significant training (prevents trigger-less outputs)
        let useDOP = sceneGap >= 4
        let dopClass: String? = useDOP ? "object" : nil

        // Target layers
        let targetLayers = rank <= 32 ? "all" : "attention"

        // Summary
        let sceneLabel = sceneGap <= 2 ? "LOW" : (sceneGap <= 5 ? "MODERATE" : "HIGH")
        let styleLabel = styleGap <= 2 ? "LOW" : (styleGap <= 5 ? "MODERATE" : "HIGH")
        let summary = "Scene gap: \(sceneLabel) (\(sceneScore)/10), Style gap: \(styleLabel) (\(styleScore)/10) → \(steps) steps, rank \(rank), \(timestepSampling) sampling"

        return LoRARecommendation(
            steps: steps,
            rank: rank,
            alpha: Float(rank),
            learningRate: 1e-4,
            warmupSteps: max(10, steps / 10),
            timestepSampling: timestepSampling,
            lossWeighting: "bell_shaped",
            targetLayers: targetLayers,
            useDOP: useDOP,
            dopClass: dopClass,
            useGradientCheckpointing: needsGradientCheckpoint,
            summary: summary
        )
    }
}
